// Lead scoring from the concept's table. n8n's Code node runs a copy of this
// file (generated by `pnpm n8n:score`), so the unit tests cover what n8n runs.
// Keep it dependency-free.

export type ScoreInput = {
  type: 'builder' | 'contact' | 'demo' | 'career' | 'booking'
  pillars: string[]
  storeToSystem: boolean
  timeline?: string
  registered?: boolean
  size?: string
  location?: string
  budgetMax?: number
  estimateLow?: number
}

export type Tier = 'hot' | 'warm' | 'nurture'

export function scoreLead(l: ScoreInput): { score: number; tier: Tier; reasons: string[] } {
  let score = 0
  const reasons: string[] = []
  const add = (n: number, why: string) => {
    score += n
    reasons.push(`+${n} ${why}`)
  }

  if (l.budgetMax != null && l.estimateLow != null && l.estimateLow > 0 && l.budgetMax >= l.estimateLow)
    add(30, 'budget meets estimate low end')
  if (l.pillars.length >= 2 || l.storeToSystem) add(20, 'two or more pillars or Store to System')
  if (l.timeline === 'under-1m' || l.timeline === '1-3m') add(15, 'timeline within 3 months')
  if (l.registered || l.size === '10-49' || l.size === '50+') add(15, 'registered company or 10+ staff')
  if (l.pillars.includes('retail') || l.type === 'demo') add(10, 'retail design or product demo')
  if (l.location === 'overseas' || l.location === 'intl') add(10, 'international')

  const tier: Tier = score >= 70 ? 'hot' : score >= 40 ? 'warm' : 'nurture'
  return { score, tier, reasons }
}
