// GENERATED by `pnpm n8n:score` from src/lib/scoring.ts. Do not edit here.
// Lead scoring from the concept's table. n8n's Code node runs a copy of this
// file (generated by `pnpm n8n:score`), so the unit tests cover what n8n runs.
// Keep it dependency-free.
function scoreLead(l) {
    let score = 0;
    const reasons = [];
    const add = (n, why) => {
        score += n;
        reasons.push(`+${n} ${why}`);
    };
    if (l.budgetMax != null && l.estimateLow != null && l.estimateLow > 0 && l.budgetMax >= l.estimateLow)
        add(30, 'budget meets estimate low end');
    if (l.pillars.length >= 2 || l.storeToSystem)
        add(20, 'two or more pillars or Store to System');
    if (l.timeline === 'under-1m' || l.timeline === '1-3m')
        add(15, 'timeline within 3 months');
    if (l.registered || l.size === '10-49' || l.size === '50+')
        add(15, 'registered company or 10+ staff');
    if (l.pillars.includes('retail') || l.type === 'demo')
        add(10, 'retail design or product demo');
    if (l.location === 'overseas' || l.location === 'intl')
        add(10, 'international');
    const tier = score >= 70 ? 'hot' : score >= 40 ? 'warm' : 'nurture';
    return { score, tier, reasons };
}

// ---- n8n Code node ("Run once for each item") ----
const lead = $json.body ?? $json
const est = lead.estimate ?? {}
const d = lead.derived ?? {}
const a = lead.answers ?? {}
const result = scoreLead({
  type: lead.type,
  pillars: a.what?.pillars ?? [],
  storeToSystem: !!d.storeToSystem,
  timeline: a.timeline,
  registered: a.business?.registered,
  size: a.business?.size,
  location: a.business?.location ?? (lead.attribution?.country && lead.attribution.country !== 'LK' ? 'overseas' : 'LK'),
  // Budget band and estimate share a currency only when the visitor kept it; compare like with like.
  budgetMax: d.budgetCur === est.cur ? (d.budgetMax ?? Number.MAX_SAFE_INTEGER) : undefined,
  estimateLow: est.low,
})
return { json: { ...lead, score: result.score, tier: result.tier, scoreReasons: result.reasons } }
