/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pillars: Pillar;
    'case-studies': CaseStudy;
    products: Product;
    'rate-card': RateCard;
    testimonials: Testimonial;
    team: Team;
    careers: Career;
    pages: Page;
    media: Media;
    users: User;
    lead_outbox: LeadOutbox;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pillars: PillarsSelect<false> | PillarsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'rate-card': RateCardSelect<false> | RateCardSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    lead_outbox: LeadOutboxSelect<false> | LeadOutboxSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    pricing: Pricing;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars".
 */
export interface Pillar {
  id: number;
  key: 'retail' | 'software' | 'web' | 'brand';
  name: string;
  /**
   * URL segment. Lowercase, hyphens only (generated from name if empty).
   */
  slug: string;
  accent: 'lilac' | 'tangerine' | 'aqua' | 'lime';
  oneLiner: string;
  /**
   * Use the target search phrase, e.g. "retail store design in Sri Lanka".
   */
  h1: string;
  intro: string;
  capabilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  tools?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  fromPriceLKR: number;
  fromPriceUSD: number;
  seo?: {
    /**
     * Under 60 characters. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Under 160 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Stored in Azure Blob behind the CDN. Loops: 1280px, muted, 6 to 8 s, under 1.5 MB (see scripts/encode.sh).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what is shown. Required for every file.
   */
  alt: string;
  /**
   * Required for video: the frame shown before the loop plays and under reduced motion.
   */
  poster?: (number | null) | Media;
  /**
   * Optional extra encodes. The main upload should be the H.264 MP4.
   */
  sources?: {
    av1?: (number | null) | Media;
    webm?: (number | null) | Media;
    /**
     * 720x1280 crop for phones
     */
    vertical?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  client: string;
  /**
   * URL segment. Lowercase, hyphens only (generated from client if empty).
   */
  slug: string;
  logo?: (number | null) | Media;
  industry: string;
  location: 'LK' | 'intl';
  pillars: ('retail' | 'software' | 'web' | 'brand')[];
  /**
   * One line: the outcome, with a number if possible.
   */
  result: string;
  brief: string;
  approach?:
    | {
        pillar: 'retail' | 'software' | 'web' | 'brand';
        body: string;
        id?: string | null;
      }[]
    | null;
  metrics?:
    | {
        label: string;
        value: string;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Cover frame. Needed before publishing; the site shows a placeholder slate until then.
   */
  cover?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  video?: (number | null) | Media;
  quote?: (number | null) | Testimonial;
  /**
   * Shown in the window title bar, e.g. grocer-flagship.case
   */
  windowFileName: string;
  /**
   * Shows on the home Work beat.
   */
  featured?: boolean | null;
  publishedAt: string;
  seo?: {
    /**
     * Under 60 characters. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Under 160 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  person: string;
  role?: string | null;
  company: string;
  caseStudy?: (number | null) | CaseStudy;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * URL segment. Lowercase, hyphens only (generated from name if empty).
   */
  slug: string;
  /**
   * Short label drawn on the dock icon, e.g. POS
   */
  glyph: string;
  accent: 'lilac' | 'tangerine' | 'aqua' | 'lime';
  appIcon?: (number | null) | Media;
  pitch: string;
  audience: string;
  features?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Monthly prices. The first plan is what the project builder adds.
   */
  plans?:
    | {
        name: string;
        highlight?: boolean | null;
        LKR: number;
        USD: number;
        yearlyDiscountPct?: number | null;
        setupLKR: number;
        setupUSD: number;
        id?: string | null;
      }[]
    | null;
  demoUrl?: string | null;
  /**
   * Phase 2
   */
  trialUrl?: string | null;
  screenRecording?: (number | null) | Media;
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Under 60 characters. Falls back to the page title.
     */
    title?: string | null;
    /**
     * Under 160 characters.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Drives the project builder estimate. Changes revalidate every page that shows a price.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-card".
 */
export interface RateCard {
  id: number;
  pillar: 'retail' | 'software' | 'web' | 'brand';
  unit: 'project' | 'sqft';
  basePriceLKR: number;
  basePriceUSD: number;
  /**
   * When the answer to a scope question matches, the base is multiplied by the factor.
   */
  multipliers?:
    | {
        /**
         * e.g. pages, modules, service
         */
        question: string;
        /**
         * e.g. 6-15, web-mobile
         */
        answer: string;
        factor: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  /**
   * Short muted loop or a still.
   */
  portraitLoop?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  /**
   * URL segment. Lowercase, hyphens only (generated from title if empty).
   */
  slug: string;
  type: string;
  location: string;
  summary: string;
  description?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  open?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Legal pages: /legal/<slug>
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL segment. Lowercase, hyphens only (generated from title if empty).
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('admin' | 'editor' | 'pricing')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead_outbox".
 */
export interface LeadOutbox {
  id: number;
  reference: string;
  type: string;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attempts?: number | null;
  lastError?: string | null;
  delivered?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pillars';
        value: number | Pillar;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'rate-card';
        value: number | RateCard;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'lead_outbox';
        value: number | LeadOutbox;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars_select".
 */
export interface PillarsSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  slug?: T;
  accent?: T;
  oneLiner?: T;
  h1?: T;
  intro?: T;
  capabilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  tools?:
    | T
    | {
        item?: T;
        id?: T;
      };
  fromPriceLKR?: T;
  fromPriceUSD?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  client?: T;
  slug?: T;
  logo?: T;
  industry?: T;
  location?: T;
  pillars?: T;
  result?: T;
  brief?: T;
  approach?:
    | T
    | {
        pillar?: T;
        body?: T;
        id?: T;
      };
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  cover?: T;
  gallery?: T;
  video?: T;
  quote?: T;
  windowFileName?: T;
  featured?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  glyph?: T;
  accent?: T;
  appIcon?: T;
  pitch?: T;
  audience?: T;
  features?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  plans?:
    | T
    | {
        name?: T;
        highlight?: T;
        LKR?: T;
        USD?: T;
        yearlyDiscountPct?: T;
        setupLKR?: T;
        setupUSD?: T;
        id?: T;
      };
  demoUrl?: T;
  trialUrl?: T;
  screenRecording?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-card_select".
 */
export interface RateCardSelect<T extends boolean = true> {
  pillar?: T;
  unit?: T;
  basePriceLKR?: T;
  basePriceUSD?: T;
  multipliers?:
    | T
    | {
        question?: T;
        answer?: T;
        factor?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  person?: T;
  role?: T;
  company?: T;
  caseStudy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  portraitLoop?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  location?: T;
  summary?: T;
  description?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  open?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  poster?: T;
  sources?:
    | T
    | {
        av1?: T;
        webm?: T;
        vertical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead_outbox_select".
 */
export interface LeadOutboxSelect<T extends boolean = true> {
  reference?: T;
  type?: T;
  payload?: T;
  attempts?: T;
  lastError?: T;
  delivered?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  stats: {
    clients: number;
    team: number;
    products: number;
    years: number;
  };
  openForProjects?: boolean | null;
  /**
   * International format, e.g. +94770000000
   */
  whatsapp: string;
  phone: string;
  email: string;
  /**
   * Cal.com or Calendly link
   */
  bookingUrl: string;
  office: {
    line1: string;
    city: string;
    country: string;
    mapUrl?: string | null;
  };
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  founderNote: {
    quote: string;
    name: string;
    role: string;
    /**
     * Founder video with WebVTT captions
     */
    video?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Tune the builder estimate without a deploy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  /**
   * Saving when 2+ retail pieces are picked (0.1 = 10%).
   */
  bundleSavingPct: number;
  /**
   * High end = low end x this.
   */
  rangeWidth: number;
  roundLKR: number;
  roundUSD: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        clients?: T;
        team?: T;
        products?: T;
        years?: T;
      };
  openForProjects?: T;
  whatsapp?: T;
  phone?: T;
  email?: T;
  bookingUrl?: T;
  office?:
    | T
    | {
        line1?: T;
        city?: T;
        country?: T;
        mapUrl?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  founderNote?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        video?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  bundleSavingPct?: T;
  rangeWidth?: T;
  roundLKR?: T;
  roundUSD?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}